spring:
  datasource:
    url: jdbc:mysql://localhost:3306/3week  # ??? MySQL ??????? ??
    username: root                                   # ?? MySQL ??? ??
    password: djaaktkfkd88!                                # ?? MySQL ????
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL ???? ???

  jpa:
    hibernate:
      ddl-auto: update     # ??? ?? ?? (create, update, validate, none ? ? 1)
    show-sql: true         # ???? SQL? ??? ??
    properties:
      hibernate:
        format_sql: true   # SQL ??? ?? ?? ?? (???)

logging:
  level:
    org.hibernate.SQL: debug                  # ???? SQL ?? ??
    org.hibernate.type.descriptor.sql: trace  # ???? ???? ? ?? ??